apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: nginx      
    run: nginx2
  name: nginx2
spec:
  containers:
   - image: nginx
     name: nginx
     ports:
            - containerPort: 80
     resources: {}
     volumeMounts:
            - name: workdir
              mountPath: /usr/share/nginx/html
  initContainers:
    - image: busybox
      name: init
      args:
        - sh
        - -c
        - echo "Hello from instance 2" > /volume/index.html
      volumeMounts:
            - name: workdir
              mountPath: /volume
  dnsPolicy: ClusterFirst
  volumes:
          - name: workdir
            emptyDir: {}
