apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: svc-nodeport
  name: svc-nodeport
spec:
  ports:
  - name: http
    port: 8080 
    nodePort: 32100
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: NodePort
status:
  loadBalancer: {}
