apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: svc-loadbalancer
  name: svc-loadbalancer
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer
status:
  loadBalancer: {}
