apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: demo-pod
---
apiVersion: v1
kind: Pod
metadata:
  name: dotnet-vault
spec:
  serviceAccountName: demo-pod
  restartPolicy: Never
  volumes:
    - name: vault-token
      emptyDir:
        medium: Memory
    - name: config
      configMap:
        name: example-vault-agent-config
        items:
          - key: vault-agent-config.hcl
            path: vault-agent-config.hcl
          - key: consul-template-config.hcl
            path: consul-template-config.hcl
    - name: shared-data
      emptyDir: {}
  initContainers:
    # Vault container
    - name: vault-agent-auth
      image: vault
      volumeMounts:
        - name: config
          mountPath: /etc/vault
        - name: vault-token
          mountPath: /home/vault
      # This assumes Vault running on local host and K8s running in Minikube using VirtualBox
      env:
        - name: VAULT_ADDR
          value: http://10.1.0.153:8200
      # Run the Vault agent
      args:
        [
          "agent",
          "-config=/etc/vault/vault-agent-config.hcl"
        ]

  containers:
    - name: dotnet-container
      image: vaultconsumer:2
      ports:
        - containerPort: 80
      volumeMounts:
        - name: vault-token
          mountPath: /home/vault