apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-web
  name: nginx-web
spec:
  containers:
  - image: nginx
    name: nginx-web
    volumeMounts:
    - name: workdir
      mountPath: /host-path/index.html
      subPath: index.html
  volumes:
    - name: workdir
      hostPath:
        path:  /mnt/c/PoznajKubernetes/volumes
