apiVersion: batch/v1beta1
kind: CronJob
metadata:
  creationTimestamp: null
  name: cj-1
spec:
  concurrencyPolicy: Allow
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: cj-1
    spec:
      template:
        metadata:
          labels:
             source: job
          creationTimestamp: null
        spec:
          containers:
          - command:
            - sh
            - -c
            - sleep 70
            image: busybox
            name: cj-1
            resources: {}
          restartPolicy: OnFailure
  schedule: '*/1 * * * *'
status: {}
