apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - args:
    - sh
    - -c
    - touch /healthy;sleep 3600
    image: busybox
    name: busybox
    resources: {}

    livenessProbe:
          periodSeconds: 1
          initialDelaySeconds: 1
          exec:
            command:
              - cat
              - /healthy

  dnsPolicy: ClusterFirst
status: {}
