apiVersion: v1
kind: Pod
metadata:
  labels:
    run: web-app
  name: web-app
spec:
  containers:
  - image: demok8s.azurecr.io/web-app:1.0.0
    name: webapp    
    imagePullPolicy: Always
  # imagePullSecrets:
  #   - name: acr-secret
  restartPolicy: Never
  serviceAccountName: acr-serviceaccount