apiVersion: apps/v1
kind: Deployment
metadata:
  name: dp-tools
  labels:
    run: tools
spec:
  replicas: 10
  minReadySeconds: 10
  strategy:
    rollingUpdate: 
      maxUnavailable: 0
      maxSurge : 1
  selector:
    matchLabels:
      app: tools
  template:
    metadata:
      labels:
        app: tools
        version: "3.0.6"
    spec:
      containers:
      - image: giantswarm/tiny-tools
        name: tools
        command: ["/bin/sh", "-c"]
        args: ["sleep 3600"]