apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc-managed-premium
spec:
  storageClassName: "managed-premium"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi