apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busyboxnode
  name: busyboxnode
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - sleep 3600
    image: busybox
    name: busyboxnode
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  nodeSelector:
          env: demo
status: {}
