apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - args:
    - sh
    - -c
    - env;sleep 3600
    image: busybox
    name: busybox
    env:
       - name: password
         valueFrom:
             secretKeyRef:
                 name: mysecret
                 key: pass3
       - name: key
         valueFrom:
              configMapKeyRef:
                  name: myconfigmap
                  key: key1
    resources: {}
    securityContext:
          capabilities:
                  add: ["NET_ADMIN", "SYS_TIME"]

    volumeMounts:
            - name: secret-volume
              mountPath: /secret
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  volumes:
   - name: secret-volume
     secret:
             secretName: mysecret
             items:
                     - key: pass3
                       path: pass/3
status: {}
