apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: sc-pod
  name: sc-pod
spec:
  containers:
  - args:
    - busybox
    - sh
    - -c
    - sleep 3600
    image: busybox
    name: pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  securityContext:
    runAsUser: 1234
status: {}
