apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: configvolume
  name: configvolume
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - cd /volume;ls -l;sleep 3600
    image: busybox
    name: configvolume
    resources: {}
    volumeMounts:
            - name: config-volume
              mountPath: /volume
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  volumes:
            - name: config-volume
              configMap:
                      name: myconfigmap
                  
status: {}
